[package]
name = "cyan_nlg"
version = "0.0.1"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["CK Vattes <cvatte1@wgu.edu>"]

[dependencies]
rust-bert = "0.16.0"
#rust-bert = "0.7.12"
#tokenizers = "0.11.0"

[dependencies.getrandom]
features = ["js"]
