[package]
name = "cyan_pwa"
version = "0.0.1"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["CK Vattes <cvatte1@wgu.edu>"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
eframe = "0.14.0"
