[package]
name = "cyan_api"
version = "0.0.1"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["CK Vattes <cvatte1@wgu.edu>"]

[dependencies]
actix-files = "0.6.0-beta.10"
actix-web = "4.0.0-beta.15"
cyan_nlg = { path = "../cyan_nlg" }
serde = "1.0.132"
serde_json = "1.0.73"
